### ISSUE TITLE
Plugin is extremely slow at startup

### ISSUE THREAD

**Issue by vn-ki** [inkarkat/vim-UnconditionalPaste#2]
I benchmarked my startup after installing this plugin and it seems to be extremely slow compared to other plugins.

```
=====================================
Top 10 plugins slowing nvim's startup
=====================================
1        17.184   vim-UnconditionalPaste
2        12.483   vim-unimpaired
3         6.532   vim-matchup
4         5.515   coc.nvim
5         3.444   tcomment_vim
6         3.363   vim-colors-xcode
7         2.073   vim-devicons
8         1.853   fzf.vim
9         1.767   asyncrun.vim
10        1.576   asynctasks.vim
=====================================
```

If you take a look, this plugin seems to be 3 times slower than coc.nvim which is an extremely huge plugin.

I'm suspecting all the startup time is wasted on creating all those maps. Maybe trim down on the number of maps (I most definitely don't use all of them), or provide an option to choose optionally from the maps.

**Comment by vn-ki** [comment]
Also, something of interest is that the top 2 extremely slow plugins are both which map a lot of keys on startup.

The unimpaired issue for interest: https://github.com/tpope/vim-unimpaired/issues/199

**Comment by inkarkat** [comment]
Is that 17 seconds or 17 milliseconds we're talking about? Multiple seconds indeed would be outrageous (but rather a Neovim issue, as several plugins are affected, and it does not happen for Vim), but I'd be perfectly content with some milliseconds. I have tons of plugins on a 7.5 years old notebook, and Vim 8.2.430 does a warm start in under 3 seconds.

That option to select just some of the provided mappings has recently been added to the code: [`:let g:UnconditionalPaste_no_mappings = 1`](https://github.com/inkarkat/vim-UnconditionalPaste/blob/286761f7cc01d65f7a904138754c45b8325047cd/doc/UnconditionalPaste.txt#L497-L501). Of course, all `<Plug>`-mappings are still created, and I don't see a way to get rid of that (short of creating a "light" version of the plugin).
